### PR TITLE
164694479: NFC Security Dashboard UI

### PR DESCRIPTION
**Pull request by Kalela**
#### What does this PR do?
Edits the Security Dashboard to have Scan Tag textview in the centre.
#### Description of Task to be completed?
- Change ConstraintLayout to Relative layout.
- Reposition activity components.
#### How should this be manually tested?
- Run the app on an NFC enabled device.
#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
#164694479
https://www.pivotaltracker.com/story/show/164694479

### CODE REVIEW

**Review by muthash — CHANGES_REQUESTED** [review]
I suggest increasing the **_Scan NFC_** font size and having a clearer message like _**Scan NFC Tag**_.

**Comment by Kalela** [comment]
Noted. Lemme see how that will look.

**Comment by Kalela** [comment]
@muthash Check the updated screenshot

**Review by muthash — APPROVED** [review]

**Comment by muthash** [comment]
LGTM

**Pull request merged**
