### PR TITLE
Use Microsoft App Centre for Testing - Build - Deploy - Monitoring - Analytics

### PR DESCRIPTION
**Pull request by daumie**
### What does this PR do?
Adds support for [Visual studio Appcenter](https://appcenter.ms) to  Build, Test, and Distribute the application. 

#### Description of Task to be completed?
- Integrate *ms appcenter's*  SDK into the applications main activity.
- Add realted  status badge

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/162710280

#### Any background context you want to add?
Developers use App Center to Build, Test, and Distribute applications. Once the app's deployed, developers monitor the status and usage of the app using the Analytics and Diagnostics services, and engage with users using the Push service.

### CODE REVIEW

**Comment by Kalela** [comment]
Hey man. Can't seem to be able to view the analytics of the app on app center. Can you give permission for devs on the team to view the results and other analytics?

**Review by Kalela — CHANGES_REQUESTED** [review]
Commented above.

**Comment by daumie** [comment]
Hey @Kalela, lemme see if this  is possible.

**Comment by Kalela** [comment]
LGTM

**Review by peternjeru — COMMENTED** [review]
Andela has no paid account with MS App Center, so this is not viable

**Review by Kalela — APPROVED** [review]

**Pull request merged**
